apiVersion: v1
kind: Secret
metadata:
  name: jfrogdockercred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ4dXNkZS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiY0dWdVoyTm9aVzVuTG5oMVFHbHVabTluWVdsdUxtTnZiVHBLWm5Kdlp6QTJPVFVoIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
